#!/bin/bash

echo "🔧 Edge Function Secrets Setup"
echo "============================="
echo ""
echo "To set up secrets for your edge functions, run these commands:"
echo ""
echo "# Set Gemini API key (required for portrait generation)"
echo "npx supabase secrets set GEMINI_API_KEY=YOUR_GEMINI_API_KEY_HERE"
echo ""
echo "# Set Stripe secret key"
echo "npx supabase secrets set STRIPE_SECRET_KEY=sk_test_YOUR_STRIPE_SECRET_KEY_HERE"
echo ""
echo "# Set Stripe webhook secret (get this from Stripe Dashboard > Webhooks > Your endpoint > Signing secret)"
echo "npx supabase secrets set STRIPE_WEBHOOK_SECRET=whsec_YOUR_WEBHOOK_SECRET_HERE"
echo ""
echo "# List current secrets (values will be hidden)"
echo "npx supabase secrets list"
echo ""
echo "⚠️  IMPORTANT: Replace YOUR_GEMINI_API_KEY_HERE, sk_test_YOUR_STRIPE_SECRET_KEY_HERE and whsec_YOUR_WEBHOOK_SECRET_HERE with actual values!"
echo ""
echo "After setting secrets, you may need to redeploy the functions:"
echo "npx supabase functions deploy portrait-generation"
echo "npx supabase functions deploy portrait-generation-simple"
echo "npx supabase functions deploy stripe-webhook"
echo "npx supabase functions deploy stripe-checkout"